#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupernodeScanner2._0.DataContextModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SupernodeScannerDB")]
	public partial class AccountHarvestedSummaryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccountHarvestedSummary(AccountHarvestedSummary instance);
    partial void UpdateAccountHarvestedSummary(AccountHarvestedSummary instance);
    partial void DeleteAccountHarvestedSummary(AccountHarvestedSummary instance);
    #endregion
		
		public AccountHarvestedSummaryDataContext() : 
				base(global::SupernodeScanner2._0.Properties.Settings.Default.SupernodeScannerDBConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public AccountHarvestedSummaryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountHarvestedSummaryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountHarvestedSummaryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccountHarvestedSummaryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AccountHarvestedSummary> AccountHarvestedSummaries
		{
			get
			{
				return this.GetTable<AccountHarvestedSummary>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccountHarvestedSummary")]
	public partial class AccountHarvestedSummary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MonitoredAccount;
		
		private long _OwnedByUser;
		
		private System.DateTime _DateOfInput;
		
		private long _FeesEarned;
		
		private long _BlockHeight;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMonitoredAccountChanging(string value);
    partial void OnMonitoredAccountChanged();
    partial void OnOwnedByUserChanging(long value);
    partial void OnOwnedByUserChanged();
    partial void OnDateOfInputChanging(System.DateTime value);
    partial void OnDateOfInputChanged();
    partial void OnFeesEarnedChanging(long value);
    partial void OnFeesEarnedChanged();
    partial void OnBlockHeightChanging(long value);
    partial void OnBlockHeightChanged();
    #endregion
		
		public AccountHarvestedSummary()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonitoredAccount", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string MonitoredAccount
		{
			get
			{
				return this._MonitoredAccount;
			}
			set
			{
				if ((this._MonitoredAccount != value))
				{
					this.OnMonitoredAccountChanging(value);
					this.SendPropertyChanging();
					this._MonitoredAccount = value;
					this.SendPropertyChanged("MonitoredAccount");
					this.OnMonitoredAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnedByUser", DbType="BigInt NOT NULL")]
		public long OwnedByUser
		{
			get
			{
				return this._OwnedByUser;
			}
			set
			{
				if ((this._OwnedByUser != value))
				{
					this.OnOwnedByUserChanging(value);
					this.SendPropertyChanging();
					this._OwnedByUser = value;
					this.SendPropertyChanged("OwnedByUser");
					this.OnOwnedByUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfInput", DbType="DateTime NOT NULL")]
		public System.DateTime DateOfInput
		{
			get
			{
				return this._DateOfInput;
			}
			set
			{
				if ((this._DateOfInput != value))
				{
					this.OnDateOfInputChanging(value);
					this.SendPropertyChanging();
					this._DateOfInput = value;
					this.SendPropertyChanged("DateOfInput");
					this.OnDateOfInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeesEarned", DbType="BigInt NOT NULL")]
		public long FeesEarned
		{
			get
			{
				return this._FeesEarned;
			}
			set
			{
				if ((this._FeesEarned != value))
				{
					this.OnFeesEarnedChanging(value);
					this.SendPropertyChanging();
					this._FeesEarned = value;
					this.SendPropertyChanged("FeesEarned");
					this.OnFeesEarnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockHeight", DbType="BigInt NOT NULL")]
		public long BlockHeight
		{
			get
			{
				return this._BlockHeight;
			}
			set
			{
				if ((this._BlockHeight != value))
				{
					this.OnBlockHeightChanging(value);
					this.SendPropertyChanging();
					this._BlockHeight = value;
					this.SendPropertyChanged("BlockHeight");
					this.OnBlockHeightChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
