<?xml version="1.0" encoding="utf-8"?><Database Name="SupernodeScannerDB" Class="AccountTxSummaryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HOME\SQLEXPRESS;Initial Catalog=SupernodeScannerDB;Integrated Security=True" SettingsObjectName="SupernodeScanner2._0.Properties.Settings" SettingsPropertyName="SupernodeScannerDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccountTxSummary" Member="AccountTxSummaries">
    <Type Name="AccountTxSummary">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MonitoredAccount" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="OwnedByUser" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DateOfInput" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Recipient" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="AmountIn" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AmountOut" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>